### ISSUE TITLE
The media query for max-width 375

### ISSUE THREAD

**Issue by ghassanmas** [FACN4/KhanWebDevelopers#19]
In the query you set the body font-size for 18px, however you have also set it to 18px by default.
So I don't see the point of overriding the font size of again.

https://github.com/FACN4/KhanWebDevelopers/blob/adfc564a9a0de67220c958576d220ba8cc7a7fd5/style.css#L14

https://github.com/FACN4/KhanWebDevelopers/blob/adfc564a9a0de67220c958576d220ba8cc7a7fd5/style.css#L188-L190

**Comment by DenisKent** [comment]
Yoosef is working on this

**Comment by yoosefkh** [comment]
@ghassanmas edited the issue

**Comment by ghassanmas** [comment]
Then this issue is no longer relevant.
