### ISSUE TITLE
more simplified code line / css .

### ISSUE THREAD

**Issue by Solk10** [FACN4/KhanWebDevelopers#22]
https://github.com/FACN4/KhanWebDevelopers/blob/adfc564a9a0de67220c958576d220ba8cc7a7fd5/style.css#L19-L22
 well you could write it more simplified as it goes clock wise.. (top - right - bottom - left)

body section{
  padding : 50px 0px 70px;
}

**Comment by haydnba** [comment]
excellent point SolK10

**Comment by ekbassa** [comment]
this issue was fixed
